### ISSUE TITLE
add ws message types and subtypes

### ISSUE THREAD

**Issue by bobanko** [StepanoidTeam/PowerGridApi#11]
### auth (user)
  - login - username/id
  - logout - username/id

### rooms
- create
- delete room?
- join
- leave/kick
- start Game

- toggleReady - only in your room

## format

- type? 
- method? (subtype)

**Comment by fatal10error** [comment]
1) delete room implementation in ticket - https://github.com/StepanoidTeam/PowerGridApi/issues/18
2) messages about events will be broadcast in different format (different values requires according to subscriber. for example when broadcast for room users - they want so see only detailed info, but generic info they already knows, and all other users want to know only users qty was changed, they really don't cares WHO especially joined/leaved)
3) so added back BroadcastReason with reason why such message was sent and added EntityType property for each broadcast message

**Comment by fatal10error** [comment]
what especially should be done for this ticket?
