### ISSUE TITLE
delete users after logout from server

### ISSUE THREAD

**Issue by bobanko** [StepanoidTeam/PowerGridApi#12]

**Comment by fatal10error** [comment]
remove it from any channels, rooms and etc.

**Comment by fatal10error** [comment]
Actually it's removed now. Just I believe it's good idea to left it on server for some time. Just in case he is going to return back. Otherwise of course delete it from any place after some timeout

**Comment by fatal10error** [comment]
not completely removed. For example if he is in room, he will be there after logout forever

**Comment by fatal10error** [comment]
done
