### ISSUE TITLE
Раздача денег игрокам (Бюрократия)

### ISSUE THREAD

**Issue by bobanko** [StepanoidTeam/PowerGridApi#22]
срабатывает после затопления домов
у каждого игрока проверяется общее/затопленное количество домов

если у игрока есть дома (вообще) то он получает бабла по таблице (по колву затопленых):
https://goo.gl/LrIQWs

если у игрока нету домов вообще, то он получает 50 электро (случай с началом игры)
ЛИБО привязать получение базовых 50 к 0 этапу:
изначально (0 этап) у всех 0 городов, получают по 50 электро

**Comment by fatal10error** [comment]
doe
