### ISSUE TITLE
add Game status

### ISSUE THREAD

**Issue by bobanko** [StepanoidTeam/PowerGridApi#29]
Websockets send:
- current player move > this player is current
- player order (1,2,3 sort)
- phase changed

API methid:
Game/Status - player order, current player, phase / stage / all Buildings

**Comment by bobanko** [comment]
sample of client code

var resp = { 
  current: 333,
  order: [111,222,333,444,555],
  phase: 'auction'
}

currentChanged(resp.current);
orderChanged(resp.order);
phaseChanged(resp.phase);

**Comment by fatal10error** [comment]
done
