### ISSUE TITLE
Add apiKeys to access API

### ISSUE THREAD

**Issue by fatal10error** [StepanoidTeam/PowerGridApi#7]
API should be accessed only for predefined API Keys to prevent extra unwanted traffic + allow to customize API logic for specific API Key.
Customize on API key layer which methods should be broadcast via websockets (for example according to client implementation it can be necessary or completely unwanted to broadcast non-custom channels subscribers changes, coz such lists have strict logic, could be implemented on client and will not be needed to broadcast EXTRA responses)

**Comment by bobanko** [comment]
this api key would be public due to fact that JS source code is public
so anyone can get this "secret" key and use it
so, maybe CORS should do this work
we can set list of domains that are allowed to access api
